# Generated by Django 5.2.3 on 2025-06-28 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeNmae', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('salary', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=100)),
                ('employmentDate', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('staffbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='employees.staffbase')),
                ('department', models.CharField(max_length=255)),
                ('has_company_card', models.BooleanField(default=True)),
            ],
            bases=('employees.staffbase',),
        ),
        migrations.CreateModel(
            name='Intern',
            fields=[
                ('staffbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='employees.staffbase')),
                ('has_company_card', models.BooleanField(default=True)),
                ('internship_end', models.CharField(max_length=255)),
                ('internship_start', models.CharField(max_length=255)),
                ('mentor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intern_mentee', to='employees.manager')),
            ],
            bases=('employees.staffbase',),
        ),
    ]
